### ISSUE TITLE
Unknown Property 

### ISSUE THREAD

**Issue by m4893** [mapbox/mapbox-vision-ar-android#22]
ERROR: Could not get unknown property 'CORE_VISION_SDK' for settings 'mapbox-vision-ar-android' of type org.gradle.initialization.DefaultSettings.

**Comment by yunikkk** [comment]
This repo has been deprecated and will be archived soon. Now VisionAr resides in Vision repo at https://github.com/mapbox/mapbox-vision-android/tree/dev/MapboxVisionAR. Will close this issue and open corresponding on in Vision.

**Comment by yunikkk** [comment]
See https://github.com/mapbox/mapbox-vision-android/issues/85

**Comment by mohan9nimo** [comment]
i also have same issue

**Comment by yunikkk** [comment]
@mohan9nimo are you using latest master from https://github.com/mapbox/mapbox-vision-android/tree/master?
